In [1]:
import pandas as pd

In [2]:
#!wget ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM1436nnn/GSM1436261/suppl/GSM1436261_ENCFF002ENH.bed.gz

--2017-11-24 05:46:35--  ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM1436nnn/GSM1436261/suppl/GSM1436261_ENCFF002ENH.bed.gz
           => ‘GSM1436261_ENCFF002ENH.bed.gz’
Resolving ftp.ncbi.nlm.nih.gov (ftp.ncbi.nlm.nih.gov)... 130.14.250.10, 2607:f220:41e:250::13
Connecting to ftp.ncbi.nlm.nih.gov (ftp.ncbi.nlm.nih.gov)|130.14.250.10|:21... connected.
Logging in as anonymous ... Logged in!
==> SYST ... done.    ==> PWD ... done.
==> TYPE I ... done.  ==> CWD (1) /geo/samples/GSM1436nnn/GSM1436261/suppl ... done.
==> SIZE GSM1436261_ENCFF002ENH.bed.gz ... 118874
==> PASV ... done.    ==> RETR GSM1436261_ENCFF002ENH.bed.gz ... done.
Length: 118874 (116K) (unauthoritative)

GSM1436261_ENCFF002 100%[===================>] 116.09K   558KB/s    in 0.2s

2017-11-24 05:46:37 (558 KB/s) - ‘GSM1436261_ENCFF002ENH.bed.gz’ saved [118874]

In [3]:
GSM1436261_df=pd.read_csv('GSM1436261_ENCFF002ENH.bed.gz',sep='\t',header=None)

          0          1          2
0      chrX    2746600    2747799
1      chrX    3629400    3632599
2      chrX    3732200    3734999
3      chrX    7064600    7066799
4      chrX    7893800    7896399
5      chrX    9309800    9311599
6      chrX    9430200    9436199
7      chrX   11127600   11131199
8      chrX   11283200   11286199
9      chrX   11368600   11372599
10     chrX   11396000   11398399
11     chrX   11440800   11446599
12     chrX   11455400   11457999
13     chrX   11775400   11779399
14     chrX   12808800   12811999
15     chrX   12974400   12976799
16     chrX   12982400   12984999
17     chrX   12992000   12997199
18     chrX   13309400   13312399
19     chrX   13670400   13673599
20     chrX   13706600   13709399
21     chrX   13749600   13754999
22     chrX   14045400   14048999
23     chrX   14890000   14893799
24     chrX   15352000   15355199
25     chrX   15510600   15513199
26     chrX   15568200   15571799
27     chrX   15692000   15695999
28     chrX   15806400   15809599
29     chrX   15871400   15874999
...     ...        ...        ...
16815  chr8  145555000  145557199
16816  chr8  145560400  145563399
16817  chr8  145580400  145583199
16818  chr8  145596200  145599599
16819  chr8  145633400  145635599
16820  chr8  145638200  145639999
16821  chr8  145651000  145655199
16822  chr8  145668600  145670599
16823  chr8  145673600  145674799
16824  chr8  145682200  145683999
16825  chr8  145685800  145693599
16826  chr8  145700400  145705199
16827  chr8  145732600  145735999
16828  chr8  145741600  145745999
16829  chr8  145746400  145749999
16830  chr8  145753600  145755399
16831  chr8  145909400  145912199
16832  chr8  145978800  145981999
16833  chr8  146010800  146019599
16834  chr8  146022400  146025799
16835  chr8  146051200  146056599
16836  chr8  146066600  146071199
16837  chr8  146074000  146076199
16838  chr8  146076600  146079399
16839  chr8  146123800  146128399
16840  chr8  146155600  146158399
16841  chr8  146175400  146176799
16842  chr8  146199800  146204799
16843  chr8  146226400  146231999
16844  chr8  146276600  146279599

[16845 rows x 3 columns]